"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1$q2kcws!+h#8pj%u7-jcr(l@alzfbty%j#xne)x52i%qetfsg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
	'jazzmin',
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',

	'cafe',
	'user',

	'rest_framework',
	'rest_framework.authtoken',
	'rest_framework_swagger',
	'rest_framework_simplejwt',
	'django_filters',
	'corsheaders',
	'sorl.thumbnail',
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'corsheaders.middleware.CorsMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'core.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.sqlite3',
		'NAME': BASE_DIR / 'db.sqlite3',
	}
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Asia/Bishkek'

USE_I18N = True

USE_TZ = True

AUTH_USER_MODEL = 'user.User'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATICFILES_DIRS = [BASE_DIR / 'assets']

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TWILIO_VERIFY_SERVICE = 'VA999ef1e930113b02cb40be27b21e7b5a'
TWILIO_AUTH_TOKEN = '66a6e22a74a640ca5f1be6b6ac62389f'
TWILIO_ACCOUNT_SID = 'AC586c4ea254fc046c96bcfede2c8518e5'
MAX_DIGETS_VERIFICATION_CODE = 6

REST_FRAMEWORK = {
	'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
	'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
	'DEFAULT_AUTHENTICATION_CLASSES': (
		'rest_framework.authentication.TokenAuthentication',
		'rest_framework_simplejwt.authentication.JWTAuthentication',
		'rest_framework.authentication.SessionAuthentication',
		'rest_framework.authentication.BasicAuthentication',
	),
}

SIMPLE_JWT = {
	'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
	'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
	'ROTATE_REFRESH_TOKENS': False,
	'BLACKLIST_AFTER_ROTATION': True,
	'UPDATE_LAST_LOGIN': False,

	'ALGORITHM': 'HS256',
	'SIGNING_KEY': SECRET_KEY,
	'VERIFYING_KEY': None,
	'AUDIENCE': None,
	'ISSUER': None,

	'AUTH_HEADER_TYPES': ('Bearer',),
	'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
	'USER_ID_FIELD': 'id',
	'USER_ID_CLAIM': 'user_id',

	'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
	'TOKEN_TYPE_CLAIM': 'token_type',

	'JTI_CLAIM': 'jti',

	'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
	'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
	'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

CORS_ORIGIN_ALLOW_ALL = (
	True
)

JAZZMIN_SETTINGS = {
	# заголовок окна (по умолчанию будет current_admin_site.site_title, если он отсутствует или отсутствует)
	"site_title": "Admin",

	# Заголовок на экране входа (максимум 19 символов) (по умолчанию — current_admin_site.site_header, если он отсутствует или отсутствует)
	"site_header": "admin.kg",

	# Название бренда (максимум 19 символов) (по умолчанию — current_admin_site.site_header, если оно отсутствует или отсутствует)
	"site_brand": "Admin",

	# Логотип для вашего сайта должен присутствовать в статических файлах, используется для бренда в левом верхнем углу.
	"site_logo": '/img/main_logo.gif',

	# Классы CSS, которые применяются к логотипу выше
	"site_logo_classes": "",

	# Относительный путь к значку для вашего сайта, по умолчанию будет site_logo, если он отсутствует (в идеале 32x32 px)
	"site_icon": '/img/logo.png',

	# Приветственный текст на экране входа
	"welcome_sign": "Добро пожаловать в администрацию сайта",

	# Авторское право на нижний колонтитул
	"copyright": "PROlab",

	# Администратор модели для поиска из панели поиска, панель поиска опускается, если исключена
	"search_model": "auth.User",

	# Имя поля в модели пользователя, которое содержит аватар ImageField/URLField/Charfield или вызываемый объект, который получает пользователя
	"user_avatar": 'avatar',

	############
	# Top Menu #
	############

	# Ссылки для размещения в верхнем меню
	"topmenu_links": [

		# URL-адрес, который становится обратным (можно добавить разрешения)
		{"name": "Главная", "url": "admin:index",
		 "permissions": ["auth.view_user"]},

		# внешний URL, который открывается в новом окне (можно добавить разрешения)
		# {"name": "Jazzmin", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
		{"name": "Rest API", "url": "/api/v1/swagger/", "new_window": True},

		# Приложение с выпадающим меню для всех страниц своих моделей (разрешения проверены для моделей)
		# {"app": "books"},
	],

	#############
	# Меню пользователя#
	#############

	# Дополнительные ссылки для включения в меню пользователя в правом верхнем углу (URL-адрес типа "приложение" не разрешен)
	"usermenu_links": [
	],

	#############
	# Боковое меню #
	#############

	# Отображать ли боковое меню
	"show_sidebar": True,

	# Нужно ли автоматически расширять меню
	"navigation_expanded": True,

	# Скрыть эти приложения при создании бокового меню, например (авторизация)
	"hide_apps": [],

	# Скрыть эти модели при создании бокового меню (например, auth.user)
	"hide_models": [],

	# Список приложений (и/или моделей) для базового упорядочения бокового меню (не обязательно содержать все приложения/модели)
	"order_with_respect_to": [],

	# Пользовательские ссылки для добавления в группы приложений, вводимые по имени приложения
	# "custom_links": {
	#     "Products": [{
	#         "name": "Make Messages",
	#         "url": "make_messages",
	#         "icon": "fas fa-comments",
	#         "permissions": ["books.view_book"]
	#     }]
	# },

	# Пользовательские значки для приложений/моделей бокового меню См. https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
	# полный список бесплатных классов значков 5.13.0
	"icons": {
		'cafe.Category': 'fas fa-tags',
		'cafe.Item': 'fas fa-hamburger',
		'user.User': 'fas fa-user-circle',
		'auth.Group': 'fas fa-users',
		'authtoken.TokenProxy': 'fas fa-key',
		'cart.Cart': 'fas fa-shopping-cart',
		'cart.City': 'fas fa-city',
	},
	# Значки, которые используются, если они не указаны вручную
	"default_icon_parents": "fas fa-chevron-circle-right",
	"default_icon_children": "fas fa-circle",

	#################
	# Связанный модальный #
	#################
	# Используйте модальные окна вместо всплывающих окон
	"related_modal_active": False,

	#############
	# Настройки пользовательского интерфейса #
	#############
	# Относительные пути к пользовательским скриптам CSS/JS (должны присутствовать в статических файлах)
	"custom_css": None,
	"custom_js": '/js/admin_script.js',
	# Показывать ли настройщик пользовательского интерфейса на боковой панели
	"show_ui_builder": True,

	###############
	# Сменить вид #
	###############
	# Визуализировать представление изменений в виде отдельной формы или на вкладках, текущие параметры
	# - single
	# - horizontal_tabs (default)
	# - vertical_tabs
	# - collapsible
	# - carousel
	"changeform_format": "single",
	# переопределить формы изменений для каждой модели на основе администратора
	"changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},

}

JAZZMIN_UI_TWEAKS = {
	"navbar_small_text": False,
	"footer_small_text": False,
	"body_small_text": False,
	"brand_small_text": False,
	"brand_colour": "navbar-dark",
	"accent": "accent-primary",
	"navbar": "navbar-dark",
	"no_navbar_border": False,
	"navbar_fixed": True,
	"layout_boxed": False,
	"footer_fixed": False,
	"sidebar_fixed": True,
	"sidebar": "sidebar-dark-danger",
	"sidebar_nav_small_text": True,
	"sidebar_disable_expand": False,
	"sidebar_nav_child_indent": False,
	"sidebar_nav_compact_style": False,
	"sidebar_nav_legacy_style": False,
	"sidebar_nav_flat_style": True,
	"theme": "default",
	"dark_mode_theme": None,
	"button_classes": {
		"primary": "btn-primary",
		"secondary": "btn-outline-secondary",
		"info": "btn-info",
		"warning": "btn-warning",
		"danger": "btn-danger",
		"success": "btn-success"
	}
}
